In [1]:
#1D_Array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)



[10 20 30 40 50]


In [2]:
import numpy as np

# Create a 2D array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
print(arr)

2D Array:
[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

# Create a 3D array
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print("3D Array:")
print(arr)


3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
